INSERT INTO CAR (ID, MANUFACTURER, MODEL, OWNER, GARAGE_ID) VALUES (1, 'Ford', 'Focus', 'James', 2);
INSERT INTO CAR (ID, MANUFACTURER, MODEL, OWNER, GARAGE_ID) VALUES (2, 'BMW', '520d', 'Charlie', 4);
INSERT INTO CAR (ID, MANUFACTURER, MODEL, OWNER, GARAGE_ID) VALUES (3, 'Vauxhall', 'Astra', 'Chantelle', 1);
INSERT INTO CAR (ID, MANUFACTURER, MODEL, OWNER, GARAGE_ID) VALUES (4, 'Honda', 'Jazz', 'Anne', 3);

INSERT INTO GARAGE(ID, NAME, CAPACITY) VALUES (1, 'West Side', 30);
INSERT INTO GARAGE(ID, NAME, CAPACITY) VALUES (2, 'Maltings', 25);
INSERT INTO GARAGE(ID, NAME, CAPACITY) VALUES (1, 'Metrocentre', 100);
INSERT INTO GARAGE(ID, NAME, CAPACITY) VALUES (1, 'Drover\'s Way', 30);